### ISSUE TITLE
Changing Notebook's location 

### ISSUE THREAD

**Issue by vmexia** [tamlok/vnote#150]
It would be very useful to have an option to update the root folder of a notebook. One of my notebooks had the root on ../Users/Me/Documents and for sync reasons I decided to move it to my GDrive folder ../Users/Me/GDrive/Somewhere. I wasn't able to change that from inside Vnote, and once I tried to mess with the session.ini file nothing happened apart from asking me to create a new notebook (once I set that notebook root to the new location it worked). Although its now solved, the workaround is not intuitive, it should be a straightforward process, 

1. Can't load notebook location
2. Did it change?
3. Yes, where to? | No, delete notebook

If I'm missing the point here please feel free to correct me :)

Thanks for your work,
Vitor

**Comment by tamlok** [comment]
VNote is designed to not allow the change of the notebook location for simplicity.

For now you could **remove** (not delete) the notebook from VNote, then move the root folder to desired location outside VNote, then **Add Notebook** in VNote to import that root folder back again. VNote will detect the config files and import an existing notebook instead of creating a new one.

It is a good idea to prompt for a new location for the missing notebook. It is kind of exception handling, so it is not considered well for now. I will add it later.

Thanks.

P.S. When you delete a notebook from VNote, you could choose whether delete files in disk as well. Be carefull!!!

**Comment by tamlok** [comment]
Hi，since 1.14, VNote will prompt for the new location of the missing notebook at startup. So you could just close VNote, then move you notebook root folder to another place, then launch VNote, and now VNote will ask you the new location of the notebook.

Thanks!
