### ISSUE TITLE
Add an option to hide ".md" extension in note panel

### ISSUE THREAD

**Issue by bbsteel** [tamlok/vnote#205]
Currently there is no file other than markdown that can be managed in VNote, and so every note in note panel ends with `.md` suffix.

Can we can add an option to hide this suffix or even remove it to save some screen space?

**Comment by tamlok** [comment]
- VNote will support opening plain text source files, such as `cpp`, `java`.
- You could add all kinds of files as notes into VNote. VNote just calls the default program to open them.

So for now we just do not hide the extension of notes. BTW, I prefer showing all the details to users instead of hiding them. :)

Thanks!
