### ISSUE TITLE
Incorrect Layout After Restore the Window by Clicking the System Tray Icon

### ISSUE THREAD

**Issue by zhangzujian** [tamlok/vnote#220]
The problem happened following #219 .

I closed the window and chose to keep the system tray icon. Then I clicked the tray icon to reopen it, the window layout turned into a strange one:

![tim 20180503103626](https://user-images.githubusercontent.com/13048299/39558087-8cebd8da-4ebe-11e8-9057-34cabe131f5a.png)

I tried to close the main window and to click the tray icon again, but it was still incorrect.

**Comment by zhangzujian** [comment]
After I closed VNote completely and reopened it, the problem didn't come out again.

**Comment by tamlok** [comment]
Hi,

I cannot repro this. I think the sequence of your operations were:

1. Open VNote at the first time;
2. The init layout of VNote's first start is strange (small edit area);
3. You maximize VNote without changing VNote's layout manually;
4. Close VNote;
5. Choose to minimize VNote;
6. Restore VNote;
7. VNote shows itself in a normal state instead of the maximized state;
8. Now the initial strange layout come out.

I checked the code and did not find anything potential for a bug when restoring VNote.

Thanks!

**Comment by tamlok** [comment]
Yes, I could reproduce it. I don't know why the interface will be a mess before first restart. Since a restart after a new installation could fix this, I plan to not fix it for now.

Thanks!
