### ISSUE TITLE
Vim Mode: 跨文件间的复制粘贴

### ISSUE THREAD

**Issue by sadhen** [tamlok/vnote#26]
text yanked from one document cannot be pasted to another document

**Comment by tamlok** [comment]
Hi, VNote's Vim mode is constrained within one single edit tab, so each tab has its own registers. You could use the **selection register** `+` to access the system's clipboard, so that you could yank and paste texts among different tabs.
VNote provide a shortcut for this, `<leader>y` is the same as `"+y`, `<leader>p` is the same as `"+p`. In VNote, `<leader>` is `<space>`. You could reference the shortcuts help menu for more details about Vim mode.
Thanks very much for your attention! :)
