### ISSUE TITLE
Distinguish two note with same name

### ISSUE THREAD

**Issue by losymear** [tamlok/vnote#274]
Hope filenames in the tab prefixed with path when two notes with same name are opened. For example,  displaying `Java/Sprint Boot/introduction`&`Java/Sprint Cloud/introduction` instead of just `introduction`&`introduction`.

<img width="569" alt="java" src="https://user-images.githubusercontent.com/30641746/41703219-27959890-7565-11e8-90a6-94e8a4bb4bbb.png">

**Comment by vmexia** [comment]
I think visually speaking "Java/Sprint Boot/introduction.md" works because is short, anything longer that, ex: "Programming/Java/Spring Boot/Introduction.md", would look bad if have more than two or three tabs open. I would counter suggest two solutions:

1. On hover over the note name, show the full path to that specific note.
2. On the Folders View, expand the full path to the current note.

**Comment by tamlok** [comment]
As @vmexia said, it is not a universal solution to display part of the path to distinguish two tabs.

For now, VNote will display the full path of a tab in the title bar as well as in the tooltip when mouse hovers on that tab.

So just leave it for now.

Thanks!
