### ISSUE TITLE
[Feature Request] Support linking non-image files using link syntax

### ISSUE THREAD

**Issue by versipellis** [tamlok/vnote#395]
I'd love to see the normal link syntax of ```[text](link)``` support files on local drive, so that I can link additional documents like .pdf's using ```[this is a document](/local document.pdf)```

Thanks!

**Comment by kerHbal** [comment]
This can be done, but not perfectly.
You can manaully input the path: It works fine in all 4 circumstances.
![image](https://user-images.githubusercontent.com/11629684/45506904-9c2ffe80-b75e-11e8-9874-feddfea2a3b0.png)

**BUT** If the relative path is more than 2 levels, only the `/` is allowed. (For me because the directory symbol in Windows is `\`, I need to change it to `/`. ) 

Only the first one will work:
![image](https://user-images.githubusercontent.com/11629684/45507182-5d4e7880-b75f-11e8-9658-6246e02296b8.png)

**Comment by tamlok** [comment]
VNote 2.0 will prompt for the selection when you dropping or pasting a file in VNote: insert link, insert relative link, or insert file content.
