### ISSUE TITLE
Cyrillic text is displayed with spacing in editor

### ISSUE THREAD

**Issue by kenota** [tamlok/vnote#478]
OS Version (操作系统): macOS 10.13.6

VNote Version (VNote版本): Latest (最新) 2.1 (also happening on 2.0)

Symptoms (表现):
When I type anything in Cyrillic (Russian for example), all letters are having spacing between them. This happens only in editor, not in view window

This seems to affect MacOS but works correctly on linux.

How to Repro (如何复现):
1. Install VNote 2.1
2. Start creating note, try to paste this text: "текст с большими пробелами"
3. Observe spacing in editor window
4. Save note and load it in viewer mode. Observe that there is no spacing anymore.

Screenshots attached for reference. 

![editor-spaces](https://user-images.githubusercontent.com/1538669/47778062-ec9ef380-dced-11e8-9c58-c5c8dfe366d2.png)
![view-no-spaces](https://user-images.githubusercontent.com/1538669/47778066-f0cb1100-dced-11e8-864c-603d85f166e0.png)

**Comment by tamlok** [comment]
Hi,

Could you provide the plain text example for me to test? By the way, which font do you use in your daily life for Russian?

Thanks!

**Comment by kenota** [comment]
Here is an example file (just rename it to .md to load in VNote, or copy-paste) exhibiting the issue.

[cyrillic-issue copy.txt](https://github.com/tamlok/vnote/files/2533799/cyrillic-issue.copy.txt)

**Comment by tamlok** [comment]
Hi,

It is caused by the font set by `.mdhl` file. You could open the configuration folder in the File menu, then `themes`, then `v_pure`, then edit the `v_pure.mdhl` file.

In the `font-family` key, add your font name at front and save it.

Restart VNote to test if it works.

It is hard to find a font for every language. I will add an option to specify font family via GUI.

By the way, if you find that some shortcuts of Captain Mode do not work in Russian keyboard layout, take a look at the keyboard layout mapping in settings dialog.

Thanks!

**Comment by kenota** [comment]
@tamlok thank you for such a quick response. Changing the font in v_pure.mdhl file worked, cyrillic text is now displayed properly. I have prepended it with "Lucida Grande". 

Perhaps you can have different mdhl file per platform? Something like `v_pure_osx.mdhl`, `v_pure_linux.mdhl`, etc. On platforms like MacOS you are probably in a good position to rely on the standard system fonts to support all the languages.

Otherwise, the option to select the font family in the config dialog would also help.

Once again, thank you for such a great tool and quick response.
