### ISSUE TITLE
Wrongfully interpreted as a heading in edit mode

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#62]
Two issues (VNote 1.10):
1. In edit mode, `#` not followed by any space is interpreted as a heading. It should be viewed as normal text.
2. In edit mode, more than six `#` in a row should be viewed as normal text.

**Comment by tamlok** [comment]
Hi,

1. VNote supports 4 renderers to convert Markdown to Html. Some of them treat `#` without spaces a valid heading. Since the default renderer Markdown-it does not recognize it, I have fix the behavior of edit mode. (d943e58f133ecf9dc9fb549eb4a3216048e442b4)
2. Good catch! Already fixed. (b9a3588e293ec1bcbc0b61afbad72fd82c572739)

Thanks!

**Comment by seaspeak** [comment]
I wrongfully put "more than seven #“ in the comment, hahaha. I corrected it.
Thanks for your efforts.

**Comment by jerry011235** [comment]
@seaspeak wrongfully是副词，好像不能这么用吧。参考：[1](http://fanyi.baidu.com/#en/zh/wrongfully)，[2](http://fanyi.baidu.com/?aldtype=85#zh/en/%E6%88%91%E9%94%99%E8%AF%AF%E5%9C%B0)
I wrongfully put "more than seven #“ in the comment, hahaha. I corrected it.
I made the mistake of putting "more than seven #“ in the comment, hahaha. I have corrected it.
