### ISSUE TITLE
The cursor misplaced at the very end of the line in normal mode

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#71]
_vnote_ 1.11.
In normal mode, click mouse at the end of the line, not at any characters. The cusor should be placed on the last character, not __after__ the last character.

_vnote_
![image](https://user-images.githubusercontent.com/8821870/34078508-d17af86a-e356-11e7-8559-3efeccf23f33.png)

_gVim_
![image](https://user-images.githubusercontent.com/8821870/34081118-a4c76420-e383-11e7-8b0f-6d2511faf285.png)

**Comment by tamlok** [comment]
Hi, if you move the cursor by keyboard, the cursor will be constrained at the last character of the line. Like the VSVim, the Vim plugin for Visual Studio, cursor clicks can place the cursor after the last character, since we need this to select the whole line. So does the FakeVim, the Vim plugin for the Qt Creator.

**Comment by seaspeak** [comment]
gVim screenshot
![image](https://user-images.githubusercontent.com/8821870/34081112-933f7058-e383-11e7-9b2b-5b563ce4dfbd.png)

But if this behavoir is as expected, please close this issue.

**Comment by tamlok** [comment]
Will move the cursor one step back after a mouse click. (775fbd93dac4e715ecc43fab83ba7d05f9f317f6) We will see a cursor jump sometimes.
