### ISSUE TITLE
Type Chinese under vim normal mode in Windows 10

### ISSUE THREAD

**Issue by seaspeak** [tamlok/vnote#83]
Under normal mode, the input method seems totally being disabled? I'm not sure about this point. I tried Microsoft Pinyin, there seems no way to call on its Chinese mode?

**Comment by tamlok** [comment]
Yes! Input method makes no sense in Normal mode. VNote will automatically enable/disable the input method when you leave/enter Normal mode, so we could just leave the input method in Chinese state, and hit `Esc` to enter normal mode, and then navigate with some movement, and then enter Insert mode and continue to type in Chinese.

**Comment by seaspeak** [comment]
We still need to type Chinese/Japanese/... once in a while under Normal mode. Try command `t` or `f`.
If we have "aaaaaaaaaaaaacbbb", we can `dfc` to get "bbb". This also applies to Chinese characters.

**Comment by tamlok** [comment]
Oh~~I have never used Vim like this.

You could disable the smart IM behavior by putting this in your `vnote.ini`:

```ini
; Enable smart input method in Vim mode (disable IM in non-Insert modes)
enable_smart_im_in_vim_mode=false
```

**Comment by seaspeak** [comment]
It is unbearable without smart IM behavior, because we have to constantly switch between input methods. I guess I'll leave it on.

- I notice that gVim toggles Microsoft Pinyin off, not totally disables it. We can toggle it on if we want to input Chinese in normal mode. Not sure if _vnote_ can do the same?
- ~~Is that possible to let _vnote_ support _vim_ autocommand-events (`:h autocommand-events`)? I'm using this method to run scripts to control states of input methods.~~

Did't expect the issue will be perfected right away. It's not a big issue. You could close the issue if you want.

**Comment by tamlok** [comment]
I have tried add shortcut to enable the IM temporarily in Normal mode. It is a pity that `QTextEdit` will accept the input from the IM directly, not passing it through the Vim interpreter. Therefore, we could not let the IM in Chinese input method in Normal mode. There seems no interfaces to toggle the Chinese input method instead of disable the IM totally.

Currently I do not have much time for the Vim. Once I have time, I think the `.` dot command is at higher priority. Anyway, we could look back someday to see if we could implement this.
